raw_data_path: data/raw/Telco-Customer-Churn.csv
target_column: Churn
id_column: customerID
test_size: 0.2
random_state: 42

binary_categorical_columns:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - PaperlessBilling

onehot_categorical_columns:
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaymentMethod

numerical_columns:
  - SeniorCitizen
  - tenure
  - MonthlyCharges
  - TotalCharges